openapi: 3.1.0
info:
  title: Hacker News Scraper API
  description: A simple API to scrape Hacker News and return post data as JSON.
  version: 1.0.0
servers:
  - url: https://hacker-news-proxy.onrender.com
    description: Server
paths:
  /api/news:
    get:
      operationId: getNews
      summary: Get Hacker News posts
      description: Returns an array of Hacker News posts including the item number, title, and copiable string (content and discussion links).
      parameters:
        - name: p
          in: query
          description: The page ID for pagination. If page ID is left out, server will take the default value of 1.
          required: false
          schema:
            type: string
            example: 2
      responses:
        '200':
          description: A JSON array of Hacker News posts.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    itemNumber:
                      type: string
                      description: The item number.
                      example: "1"
                    title:
                      type: string
                      description: The title of the news post.
                      example: "Show HN: A simple hacker news scraper"
                    copiableString:
                      type: string
                      description: The string containing both content and discussion links.
                      example: "Content: https://example.com\nDiscussion: https://news.ycombinator.com/item?id=123456"
        '500':
          description: Error response if fetching data fails.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error fetching Hacker News data"

